#!/bin/sh
# $HOME/.config/i3/scripts/brightness

notify() {
    BRIGHTNESS="$(brightnessctl i | grep -oP '\(\K[^%\)]+')"
    
    if [ "$BRIGHTNESS" -eq 0 ]; then
        icon_name="display-brightness-off-symbolic"
    elif [ "$BRIGHTNESS" -le 30 ]; then
        icon_name="display-brightness-low-symbolic"
    elif [ "$BRIGHTNESS" -le 80 ]; then
        icon_name="display-brightness-medium-symbolic"
    else
        icon_name="display-brightness-high-symbolic"
    fi
    
    exec dunstify -r 100 -i "$icon_name" "Display" "Brightness: $BRIGHTNESS%"
}

case "$1" in
    up)
        brightnessctl set 10%+ -q
        notify
        ;;
    down)
        brightnessctl set 10%- -q
        notify
        ;;
    low)
        brightnessctl set 25% -q
        notify
        ;;
    high)
        brightnessctl set 75% -q
        notify
        ;;
    *)
        echo "== ! brightness: missing or invalid argument ! =="
        echo "Try again with: up | down | low | high"
        exit 2
esac

exit 0
