#!/bin/sh

B='#00000000'  # blank
C='#FFFFFF22'  # clear ish
D='#8EAF72FF'  # default
T='#FFFFFFFF'  # text
W='#B34853FF'  # wrong
V='#69B0C4FF'  # verifying
H='#E4B964FF'  # highlight

i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T       \
--wrongcolor=$T       \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$H       \
--bshlcolor=$H        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
