require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.nord"
-- require "user.nordic"
-- require "user.catppuccin"
require "user.cmp"
require "user.lsp"
require "user.illuminate"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns2"
require "user.nvim-tree"
require "user.bufferline2"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
-- require "user.alpha"
-- require "user.autocommands"
-- require "user.dap"
